timeout: 1200s
steps:
- id: 'setup'
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - |
    if [[ "$BRANCH_NAME" == "main" ]]; then
      docker build -t gcr.io/$PROJECT_ID/gcp-test:$(date '+%s') .
      docker push gcr.io/$PROJECT_ID/gcp-test:$(date '+%s')
    else
      docker build -t gcr.io/$PROJECT_ID/gcp-test:dev-$(date '+%Y-%m-%d') .
      docker push gcr.io/$PROJECT_ID/gcp-test:dev-$(date '+%Y-%m-%d')
    fi
tags:
- gcp
    
