timeout: 1200s
steps:
- id: 'setup'
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - |
    tag=$(date +%s)
    if [[ "$BRANCH_NAME" == "main" ]]; then
      files=$(git diff --name-only HEAD)
      echo $files
      docker build -t gcr.io/$PROJECT_ID/gcp-test:$tag .
      docker push gcr.io/$PROJECT_ID/gcp-test:$tag
    else
      docker build -t gcr.io/$PROJECT_ID/gcp-test:dev-$(date '+%Y-%m-%d') .
      docker push gcr.io/$PROJECT_ID/gcp-test:dev-$(date '+%Y-%m-%d')
    fi
tags:
- gcp
    
view: myview {
  sql_table_name: mytable ;;

  measure: total_sales {
    type: sum
    sql: ${sales_value} ;;
  }

  measure: RSV {
    type: number
    sql: CASE WHEN SUM(COALESCE(${sales_value}, 0)) OVER () = 0 THEN NULL ELSE ${sales_value} / SUM(COALESCE(${sales_value}, 0)) OVER () END ;;
    value_format: "0.00%"
  }

  dimension: RSV_classification {
    type: string
    sql: CASE WHEN ${RSV} IS NULL THEN NULL
              WHEN ${RSV} <= 0.05 THEN 'C'
              WHEN ${RSV} <= 0.07 THEN 'B'
              ELSE 'A'
         END ;;
  }

  dimension: category {
    type: string
    sql: ${category} ;;
  }

  dimension: sales_volume {
    type: number
    sql: ${sales_volume} ;;
  }
}


