timeout: 1200s
steps:
- id: 'setup'
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - |
    tag=$(date +%s)
    if [[ "$BRANCH_NAME" == "main" ]]; then
      files=$(git diff --name-only HEAD)
      echo $files
      docker build -t gcr.io/$PROJECT_ID/gcp-test:$tag .
      docker push gcr.io/$PROJECT_ID/gcp-test:$tag
    else
      docker build -t gcr.io/$PROJECT_ID/gcp-test:dev-$(date '+%Y-%m-%d') .
      docker push gcr.io/$PROJECT_ID/gcp-test:dev-$(date '+%Y-%m-%d')
    fi
tags:
- gcp
    
view: my_dataset {
  sql_table_name: my_project.my_dataset

  measure: total_sales {
    type: sum
    sql: ${sales_value} ;;
  }

  dimension: RSV {
    type: number
    sql: CASE WHEN ${total_sales} > 0 THEN (${sales_value} / ${total_sales}) ELSE NULL END ;;
    value_format_name: "percent_2"
  }

  dimension: RSV_classification {
    type: string
    sql: CASE
           WHEN ${RSV} >= 0 AND ${RSV} <= 0.05 THEN 'C'
           WHEN ${RSV} > 0.05 AND ${RSV} <= 0.07 THEN 'B'
           WHEN ${RSV} > 0.07 THEN 'A'
           ELSE NULL
         END ;;
  }

  dimension: category {
    type: string
    sql: ${TABLE}.category ;;
  }

  dimension: sales_value {
    type: number
    sql: ${TABLE}.sales_value ;;
  }

  dimension: sales_volume {
    type: number
    sql: ${TABLE}.sales_volume ;;
  }
}

