timeout: 1200s
steps:
- id: 'setup'
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - |
    tag=$(date +%s)
    if [[ "$BRANCH_NAME" == "main" ]]; then
      files=$(git diff --name-only HEAD HEAD~1)
      echo $files
      docker build -t gcr.io/$PROJECT_ID/gcp-test:$tag .
      docker push gcr.io/$PROJECT_ID/gcp-test:$tag
    else
      docker build -t gcr.io/$PROJECT_ID/gcp-test:dev-$(date '+%Y-%m-%d') .
      docker push gcr.io/$PROJECT_ID/gcp-test:dev-$(date '+%Y-%m-%d')
    fi
tags:
- gcp
    
