timeout: 1200s
steps:
- id: 'setup'
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - |
    echo $(date '+%Y-%m-%d')
    docker build -t gcr.io/$PROJECT_ID/gcp-test:$(date '+%Y-%m-%d')-${SHORT_SHA} .
    docker push gcr.io/$PROJECT_ID/gcp-test:$(date '+%Y-%m-%d')-${SHORT_SHA}
