FROM migrate/migrate:v4.15.2

RUN apk update && apk add gettext
RUN wget https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.1.1/cloud-sql-proxy.linux.amd64 -O cloud-sql-proxy
RUN chmod +x cloud-sql-proxy

COPY ./migrations ./migrations
COPY entry.sh /entry.sh 
COPY entry.template.sh /entry.template.sh
RUN chmod +x /entry.sh

ENTRYPOINT ["/entry.sh"]
