name: Continuous Deployment

on:
  push:
    branches:
      - main
  push:
    tags:
      - '*'

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to staging
      run: echo "Deploying to staging..."

  deploy-tag:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to production
      run: echo "Deploying to production..."
